### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DragosV29** [rundeck/terraform-provider-rundeck#112]
Hi, 

I have the following issue when running from terraform. The issue happens if you update some resources like keys or project through GUI after creating them in terraform. Once you do that the below error will occur. Expected behaviour would be to state that there have been changes or that the resource no longer exists and needs to be recreated

│ Error: Plugin did not respond
│ 
│   with module.rundeck_lab["testing"].rundeck_project.lab[0],
│   on ../../modules/rundeck_lab/rundeck_unix.tf line 1, in resource "rundeck_project" "lab":
│    1: resource "rundeck_project" "lab" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.rundeck_lab["testing"].rundeck_public_key.lab_unix[0],
│   on ../../modules/rundeck_lab/rundeck_unix.tf line 266, in resource "rundeck_public_key" "lab_unix":
│  266: resource "rundeck_public_key" "lab_unix" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.rundeck_lab["testing"].rundeck_acl_policy.lab[0],
│   on ../../modules/rundeck_lab/rundeck_unix.tf line 278, in resource "rundeck_acl_policy" "lab":
│  278: resource "rundeck_acl_policy" "lab" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.rundeck_lab["testing"].rundeck_private_key.windows_lab[0],
│   on ../../modules/rundeck_lab/rundeck_windows.tf line 127, in resource "rundeck_private_key" "windows_lab":
│  127: resource "rundeck_private_key" "windows_lab" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.rundeck_lab["testing"].rundeck_acl_policy.windows_lab[0],
│   on ../../modules/rundeck_lab/rundeck_windows.tf line 133, in resource "rundeck_acl_policy" "windows_lab":
│  133: resource "rundeck_acl_policy" "windows_lab" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-rundeck_v0.4.6 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc257f2]

goroutine 73 [running]:
github.com/terraform-providers/terraform-provider-rundeck/rundeck.PrivateKeyExists(0xc00052fc20?, {0xde1280?, 0xc000435440})
        github.com/terraform-providers/terraform-provider-rundeck/rundeck/resource_private_key.go:122 +0x1f2
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00053a600, 0xc00021c190, {0xde1280, 0xc000435440})
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:440 +0x131
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000012a98, {0xc00021c0a0?, 0x4b9f06?}, 0xc00021c0a0)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:525 +0x365
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0xdb8480?, 0xc000012a98}, {0xf73790, 0xc000270180}, 0xc0005ae600, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00042c480, {0xf77880, 0xc000172000}, 0xc00001e000, 0xc000203650, 0x14c1e90, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0xe1e
google.golang.org/grpc.(*Server).handleStream(0xc00042c480, {0xf77880, 0xc000172000}, 0xc00001e000, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xa16
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.23.0/server.go:710 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xea

Error: The terraform-provider-rundeck_v0.4.6 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by fdevans** [comment]
Hi @DragosV29 can you please provide more detailed steps to reproduce this?

**Comment by jwesty** [comment]
Hello, 

I can also replicate the issue with just running the example from the [Rundeck Docs](https://docs.rundeck.com/docs/learning/howto/terraform-jobs.html#testing-the-terraform-provider-against-the-rundeck-instance): 

```
terraform {
  required_providers {
    rundeck = {
      source = "rundeck/rundeck"
      version = "0.4.7"
    }
  }
}

provider "rundeck" {
  url         = "http://https://<rundeck_instance>:4440/"
  api_version = "45"
  auth_token  = "<api_token>"
}

resource "rundeck_project" "terraform" {
  name        = "terraform"
  description = "Sample Application Created by Terraform Plan"
  resource_model_source {
    type = "file"
    config = {
      format                    = "resourcexml"
      file                      = "/opt/rundeck/resources.xml"
      writable                  = "true"
      generateFileAutomatically = "false"
      ssh_authentication_type   = "password"
    }
  }
  extra_config = {
    "project.label" = "Terraform Example"
  }
}

resource "rundeck_job" "bounceweb" {
  name              = "HelloWorldTerraform"
  project_name      = rundeck_project.terraform.name
  node_filter_query = "name: node.*"
  description       = "Hello World from the Terraform Rundeck Provider"
  command {
    shell_command = "whoami"
  }
}

resource "rundeck_password" "terraform" {
  path     = "passwd"
  password = "<password>"
}

data "local_file" "acl" {
  filename = "${path.cwd}/user.yaml"
}

resource "rundeck_acl_policy" "example" {
  name   = "ExampleAcl.aclpolicy"
  policy = data.local_file.acl.content
}
``` 

Here's the output: 

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

rundeck_password.terraform: Creating...
rundeck_acl_policy.example: Creating...
rundeck_project.terraform: Creating...
╷
│ Error: Request cancelled
│ 
│   with rundeck_project.terraform,
│   on rundeck.tf line 16, in resource "rundeck_project" "terraform":
│   16: resource "rundeck_project" "terraform" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with rundeck_password.terraform,
│   on rundeck.tf line 44, in resource "rundeck_password" "terraform":
│   44: resource "rundeck_password" "terraform" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with rundeck_acl_policy.example,
│   on rundeck.tf line 53, in resource "rundeck_acl_policy" "example":
│   53: resource "rundeck_acl_policy" "example" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-rundeck_v0.4.7 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102f29590]

goroutine 24 [running]:
github.com/terraform-providers/terraform-provider-rundeck/rundeck.CreateOrUpdateBaseKey(0x140001905b0, {0x103285220?, 0x1400031f200}, 0x1)
        github.com/terraform-providers/terraform-provider-rundeck/rundeck/resource_base_key.go:54 +0x3a0
github.com/terraform-providers/terraform-provider-rundeck/rundeck.resourceRundeckPassword.func1(0x103187880?, {0x103285220?, 0x1400031f200?})
        github.com/terraform-providers/terraform-provider-rundeck/rundeck/resource_password.go:10 +0x28
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0x14000732c00, 0x14000130730, 0x1400014e460, {0x103285220, 0x1400031f200})
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x3dc
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0x14000732d80, 0x140002577f0, 0x14000114330?, 0x8?)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x6c
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0x14000740018, {0x14000698180?, 0x0?}, 0x14000698180)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x698
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10325c8e0?, 0x14000740018}, {0x103295db0, 0x1400024ef30}, 0x14000698120, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400044e480, {0x103299e60, 0x14000658000}, 0x1400032c000, 0x140005649f0, 0x1037c8da0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0xbbc
google.golang.org/grpc.(*Server).handleStream(0x1400044e480, {0x103299e60, 0x14000658000}, 0x1400032c000, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0x88c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.23.0/server.go:710 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xe8

Error: The terraform-provider-rundeck_v0.4.7 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by fdevans** [comment]
I think the expectation is that changes aren't made outside of Terraform.  Deleting the key manually creates a situation where the Terraform State is different from the actual state.  I'll defer to more experienced Terraform users if that's normal or not, but I do get an error in that scenario.

**Comment by jodygilbert** [comment]
This issue needs to be re-opened, Teeraform should be detecting changes and reporting them in the plan. It should not completely crash if there are changes.
